//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassportRecognize.Controls.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiplomEntities : DbContext
    {
        public DiplomEntities()
            : base("name=DiplomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Air_Stuard> Air_Stuard { get; set; }
        public virtual DbSet<Airplane> Airplane { get; set; }
        public virtual DbSet<AirShip> AirShip { get; set; }
        public virtual DbSet<Capitan> Capitan { get; set; }
        public virtual DbSet<country> country { get; set; }
        public virtual DbSet<Flight> Flight { get; set; }
        public virtual DbSet<Human> Human { get; set; }
        public virtual DbSet<Passport> Passport { get; set; }
        public virtual DbSet<Permissions> Permissions { get; set; }
        public virtual DbSet<Stuards> Stuards { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<wanted> wanted { get; set; }
    }
}
