//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassportRecognize.Controls.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permissions
    {
        public int Id { get; set; }
        public Nullable<int> AirCraft { get; set; }
        public Nullable<int> Capitan { get; set; }
    
        public virtual AirShip AirShip { get; set; }
        public virtual Capitan Capitan1 { get; set; }
    }
}
